[17기 정희영&허민지] AccommodationDetailView 기능 구현 완료 및 AccommodationListView Filter 필터링 수정
wecode-bootcamp-korea/17-2nd-OurRealTrip-backend pull request #11
Opened 2021-03-10 11:29 UTC by mjhuh263

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-  AccommodationListView 필터링 수정 및 AccommodationDetailView 기능 구현했습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 숙소 리스트 필터링을 변경했습니다. 딕셔너리에서 if문 한개 그리고 나머지는 Q객체로 전환했습니다. 
- 숙소 상세 페이지 구현했습니다. 
- 숙소 상세 페이지 unit test 완료했습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-10 12:34 UTC, mjhuh263 commented
test.py에 Accommodation.DoesNotExist 예외처리를 깜빡했습니다. 추가한 다음 label 추가하겠습니다 :)

2021-03-10 15:21 UTC, mjhuh263 commented
Accommodation.DoesNotExist 예외 처리 추가했습니다!

2021-03-11 00:50 UTC, mjhuh263 commented
필수로 들어오는 값이라 이렇게 선언했습니답

`q = (Q(city__name=city) 
            & Q(room__maximum_capacity__gte=guest) 
            & Q(rate__gte=rate) 
            & ~Q(room__unavailabledate__start_date__gte=start_date, room__unavailabledate__end_date__lte=end_date)
        )`

2021-03-11 01:46 UTC, ulfrid requested changes
확인 바랍니다~!

2021-03-11 01:46 UTC, ulfrid commented on accommodation/views.py
> +                'main_image'    : accommodation.accommodationimage_set.first().image_url,
```suggestion
                'main_image'    : accommodation.accommodationimage_set.first().image_url,
```
first() 장고에 있는 좋은 메소드를 사용했다는 측면에서는 좋은 코드이나, 조금더 확장해서 성능적인 측면에 대해서 생각해보자면, 
all()[0]이 더 나을 수 있습니다. 
왜 그런지 확인해보고 답해주세요.

2021-03-11 01:48 UTC, mjhuh263 commented on accommodation/views.py
> +                'main_image'    : accommodation.accommodationimage_set.first().image_url,
넵! 공부하고 다시 코멘트 남기겠습니다!

2021-03-11 02:40 UTC, mjhuh263 commented on accommodation/views.py
> +                'main_image'    : accommodation.accommodationimage_set.first().image_url,
아주 소박한 추측 | first() 메소드는 아무것도 안들어오면 None을 반환하지만... all()[0]은 IndexError를 반환하기 때문이라고 생각합니다..!!!!!

2021-03-11 05:04 UTC, ulfrid commented on accommodation/views.py
> +                'main_image'    : accommodation.accommodationimage_set.first().image_url,
네 현재상황에서는 first()가 큰 영향이 없는데, 캐싱된 데이터를 순회할 경우에는 first() 사용시 DB hit가 더 발생하고,  all()[0] 시에는 발생되지 않습니다. 추후에 적용 바랍니다. 현재 get은 근데 아에 데이터 캐싱이 없었네요 ㅋㅋ

2021-03-11 05:13 UTC, ulfrid commented
LGTM 👍

2021-03-11 05:13 UTC, merged

2021-03-11 07:42 UTC, mjhuh263 commented on accommodation/views.py
> +                'main_image'    : accommodation.accommodationimage_set.first().image_url,
앗 알려주셔서 감사합니다 지훈님!!

2021-03-11 10:28 UTC, mjhuh263 commented
force push 했는데 history에 왜 안뜨는걸까요...??지훈님..? 식은땀 납니다...

2021-03-11 10:38 UTC, mjhuh263 commented
merge된 PR에서 난리쳤습니다.. 정신 차리고 오겠습니다..